### ISSUE TITLE
Media Library doesn't work when module active

### ISSUE THREAD

**Issue by InternetMedicineMan** [experius/Mage2-Module-WysiwygDownloads#16] opened 2018-07-12 18:11 UTC
So I installed the module and tried to use it. 

When on a page and create a link and try to browse the Media Library the slide out is blank, and on the product page in the background I get the following error:

"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

Running:
Magento 2.2.4
PHP 7
Apache 2

When I turn the module off everything works fine again.

**Comment by lewisvoncken** [comment] 2018-10-05 10:04
@InternetMedicineMan 
can you please give some more information how to reproduce?

**Comment by InternetMedicineMan** [comment] 2018-10-05 16:10
Enable the module on 2.2.4 and the media library slide out is blank. That's it. I haven't tested on 2.2.5 because after this long delay in response I had to move on to a different solution.

**Comment by LiamKarlMitchell** [comment] 2020-05-27 22:14
Seems to be an issue on Magento 2.3.2 as well.
Closing the media library and re-opening it again seems to fix I think this was a known issue but I forget the issue number.

**Comment by roman204** [comment] 2022-11-05 08:14
Deprecated Functionality: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/htdocs/vendor/experius/module-wysiwygdownloads/Helper/Settings.php on line 86

**Comment by borisvankatwijk** [comment] 2024-01-10 10:22
@roman204 ,

This issue has been resolved in another PR:
https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/pull/23

This will release this -, or next week.

We are closing this issue (since 2.2 is no longer supported and later versions should be working correctly).

Kind regards

**Closed as completed by borisvankatwijk** 2024-01-10 10:22 UTC
